# Node.js with Angular

trigger:
- dev
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    cd ./root-web
    ng build --prod
  displayName: 'npm install and build'