export const alerts = {
    requestError: 'Request error!',
    successRegister: 'Successfull registration :)',
    logout: 'You got off system!',
    successLogin: 'Successfull authorization :)',
    userExists: 'User already exists!',
    userDoesntExist: "User doesn't exist",
    incorrectPassword: 'Incorrect password',
    needAuth: 'Login is necessary to visit this route',
    serverError: 'Server error!',
    pageNotFound: 'Page data not found :(',
    successUpdatePassword: 'Password successfully updated!',
    successUpdateEmail: 'Email successfully updated!',
    successUpdatePhoto: 'Photo successfully updated!',
} as const;
